[package]
name = "nayms-on-near-types"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = { version = "5.1", features = ["abi"] }
serde = { version = "1", features = ["derive"] }
