[workspace]
members = ["near-contract", "common-types"]
exclude = ["target"]
resolver = "2"

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true
